### ISSUE TITLE
Configuration File Issue

### ISSUE THREAD

**Issue by Mjmajicemerald7** [danjono/Inventory-Rollback#32]
A player in my server wants to be the highest deaths on the leaderboard. But after he dies ~ 300 times, the console errors out each death after that: https://mcpaste.io/d7007f4cec3d179b. The reason is that the plugin keeps writing a random integer at the bottom of the config: http://prntscr.com/tou0kf. Even though the error doesn't cause any problems, I would rather my console not get spammed with junk : )

Any help is greatly appreciated.

**Comment by wysohn** [comment]
Same problem

```
13:16:11 [SEVERE] survival > Cannot load plugins/InventoryRollback/saves/deaths/64540a80-8eb1-36e3-afb5-5a4a404ad450.yml
13:16:11 [INFO] survival > org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
13:16:11 [INFO] survival >  in 'string', line 3782, column 1:
13:16:11 [INFO] survival >     0
13:16:11 [INFO] survival >     ^
13:16:11 [INFO] survival > could not find expected ':'
13:16:11 [INFO] survival >  in 'string', line 3783, column 1:
13:16:11 [INFO] survival >     
13:16:11 [INFO] survival >     ^
13:16:11 [INFO] survival > 
13:16:11 [INFO] survival >     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:186) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at me.danjono.inventoryrollback.data.PlayerData.findPlayerData(PlayerData.java:71) ~[?:?]
13:16:11 [INFO] survival >     at me.danjono.inventoryrollback.data.PlayerData.<init>(PlayerData.java:30) ~[?:?]
13:16:11 [INFO] survival >     at me.danjono.inventoryrollback.inventory.SaveInventory.createSave(SaveInventory.java:42) ~[?:?]
13:16:11 [INFO] survival >     at me.danjono.inventoryrollback.listeners.EventLogs.playerDeath(EventLogs.java:46) ~[?:?]
13:16:11 [INFO] survival >     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1035) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1017) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:878) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1823) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1159) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:833) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.Entity.entityBaseTick(Entity.java:490) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityLiving.entityBaseTick(EntityLiving.java:265) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.Entity.tick(Entity.java:447) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityLiving.tick(EntityLiving.java:2417) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityHuman.tick(EntityHuman.java:156) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.EntityPlayer.playerTick(EntityPlayer.java:503) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:159) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1379) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
13:16:11 [INFO] survival > Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
13:16:11 [INFO] survival >  in 'string', line 3782, column 1:
13:16:11 [INFO] survival >     0
13:16:11 [INFO] survival >     ^
13:16:11 [INFO] survival > could not find expected ':'
13:16:11 [INFO] survival >  in 'string', line 3783, column 1:
13:16:11 [INFO] survival >     
13:16:11 [INFO] survival >     ^
13:16:11 [INFO] survival > 
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.1.jar:git-Paper-133]
13:16:11 [INFO] survival >     ... 36 more

```

**Comment by wysohn** [comment]
```
21:43:17 [SEVERE] survival > Cannot load plugins/InventoryRollback/saves/worldChanges/2a708cdd-25e3-37ff-b375-16eb3301d69d.yml
21:43:17 [INFO] survival > org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
21:43:17 [INFO] survival >  in 'string', line 148, column 1:
21:43:17 [INFO] survival >     2
21:43:17 [INFO] survival >     ^
21:43:17 [INFO] survival > could not find expected ':'
21:43:17 [INFO] survival >  in 'string', line 149, column 1:
21:43:17 [INFO] survival >     
21:43:17 [INFO] survival >     ^
21:43:17 [INFO] survival > 
21:43:17 [INFO] survival >     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:186) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at me.danjono.inventoryrollback.data.PlayerData.findPlayerData(PlayerData.java:71) ~[?:?]
21:43:17 [INFO] survival >     at me.danjono.inventoryrollback.data.PlayerData.<init>(PlayerData.java:30) ~[?:?]
21:43:17 [INFO] survival >     at me.danjono.inventoryrollback.inventory.SaveInventory.createSave(SaveInventory.java:42) ~[?:?]
21:43:17 [INFO] survival >     at me.danjono.inventoryrollback.listeners.EventLogs.playerChangeWorld(EventLogs.java:57) ~[?:?]
21:43:17 [INFO] survival >     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:880) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:819) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.entity.CraftEntity.teleport(CraftEntity.java:522) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at nl.martenm.servertutorialplus.points.ServerTutorialPoint.playDefault(ServerTutorialPoint.java:105) ~[?:?]
21:43:17 [INFO] survival >     at nl.martenm.servertutorialplus.points.ServerTutorialPoint$1.start(ServerTutorialPoint.java:81) ~[?:?]
21:43:17 [INFO] survival >     at nl.martenm.servertutorialplus.objects.TutorialController.finishPoint(TutorialController.java:139) ~[?:?]
21:43:17 [INFO] survival >     at nl.martenm.servertutorialplus.points.ServerTutorialPoint$1$1.run(ServerTutorialPoint.java:86) ~[?:?]
21:43:17 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
21:43:17 [INFO] survival > Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
21:43:17 [INFO] survival >  in 'string', line 148, column 1:
21:43:17 [INFO] survival >     2
21:43:17 [INFO] survival >     ^
21:43:17 [INFO] survival > could not find expected ':'
21:43:17 [INFO] survival >  in 'string', line 149, column 1:
21:43:17 [INFO] survival >     
21:43:17 [INFO] survival >     ^
21:43:17 [INFO] survival > 
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.1.jar:git-Paper-135]
21:43:17 [INFO] survival >     ... 26 more

```
