### ISSUE TITLE
InvalidConfigurationException

### ISSUE THREAD

**Issue by jonaasmith** [danjono/Inventory-Rollback#4]
Completely locks the server and causes it to crash.

```[08:32:06] [Server thread/ERROR]: Cannot load plugins/InventoryRollback/saves/deaths/51a5efe5-a63b-4ffe-a89f-6c9aba4f057a.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 2201, column 1:
    5
    ^
could not find expected ':'
 in 'string', line 2202, column 1:
    
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.14.4.jar:git-Paper-156]
	at me.danjono.inventoryrollback.data.PlayerData.findPlayerData(PlayerData.java:71) ~[?:?]
	at me.danjono.inventoryrollback.data.PlayerData.<init>(PlayerData.java:30) ~[?:?]
	at me.danjono.inventoryrollback.inventory.SaveInventory.createSave(SaveInventory.java:42) ~[?:?]
	at me.danjono.inventoryrollback.listeners.EventLogs.playerDeath(EventLogs.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-156]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:223) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:964) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:863) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:996) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1682) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity0(EntityHuman.java:862) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1087) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:785) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:751) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityGuardian$PathfinderGoalGuardianAttack.e(SourceFile:451) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55) ~[patched_1.14.4.jar:git-Paper-156]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_212]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:662) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2528) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:504) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityGuardian.movementTick(SourceFile:299) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2317) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.EntityMonster.tick(EntityMonster.java:37) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-156]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 2201, column 1:
    5
    ^
could not find expected ':'
 in 'string', line 2202, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:464) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.14.4.jar:git-Paper-156]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.14.4.jar:git-Paper-156]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.14.4.jar:git-Paper-156]
	... 49 more```

**Comment by danjono** [comment]
Line 2201 the timestamp key has become corrupt for the player save you are trying to access. Either remove the whole key from the yml file or delete the whole file and allow it to regenerate.
